export type Outreach = {
  id: string;
  leadId: string;
  auditId: string;
  channel: string;
  recommendation: string;
  status: string;
  reviewStatus: string;
  fitReason: string;
  bestAngle: string;
  generatedSubject: string | null;
  generatedBody: string | null;
  subject: string | null;
  body: string | null;
  reasoning: string;
  evidence: string[];
  reviewedAt: string | null;
  sentAt: string | null;
  sendAttemptCount: number;
  lastSendAttemptAt: string | null;
  lastSendErrorCode: string | null;
  lastSendError: string | null;
  lastSendRetryable: boolean;
  deliveryProvider: 'resend' | null;
  providerMessageId: string | null;
  createdAt: string;
  execution: {
    recipientEmail: string | null;
    senderIdentity: string | null;
    senderMode: 'configured' | 'development' | 'missing';
    senderProvider: 'resend';
    senderDomain: string | null;
    senderReadiness: 'production_ready' | 'development_only' | 'unverified' | 'missing';
    productionReady: boolean;
    telemetryMode: 'workspace_only' | 'webhook_backed';
    webhookEndpointUrl: string | null;
    webhookHosting: 'stable_public' | 'temporary_tunnel' | 'not_configured';
    webhookHostingReady: boolean;
    webhookHostingWarning: string | null;
    canSend: boolean;
    blockingReason: string | null;
  };
  delivery: {
    provider: 'resend' | null;
    providerMessageId: string | null;
    summary: {
      totalEvents: number;
      latestEventType: string | null;
      latestEventAt: string | null;
      deliveredCount: number;
      openedCount: number;
      clickedCount: number;
      bouncedCount: number;
      complainedCount: number;
      failedCount: number;
    };
    recentEvents: Array<{
      id: string;
      eventType: string;
      occurredAt: string;
      recordedAt: string;
      summary: string | null;
      errorCode: string | null;
      retryable: boolean;
      providerMessageId: string | null;
    }>;
  };
};
